apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "local-path-provisioner.serviceAccountName" . | quote }}
  namespace: {{ include "local-path-provisioner.namespace" . | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
