all:
  children:
    control_plane:
      hosts:
        controller:
          ansible_host: k8s-control-01.tail579279.ts.net
          node_hostname: k8s-control-01
          node_role: control
          node_ip: 192.168.0.150
          primary_interface: enp1s0

    workers:
      hosts:
        az:
          ansible_host: k8s-worker-01.tail579279.ts.net
          node_hostname: k8s-worker-01
          node_role: worker
          node_ip: 192.168.0.24
          primary_interface: enp3s0

  vars:
    ansible_user: root
    ansible_become: false
    ansible_python_interpreter: /usr/bin/python3
