apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertmanager-discord
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/hunsy9/hunsy-homelab.git
      targetRevision: main
      path: charts/alertmanager-discord
      helm:
        releaseName: alertmanager-discord
        valueFiles:
          - $values/sites/controller/alertmanager-discord/values.yaml
    - repoURL: https://github.com/hunsy9/hunsy-homelab.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
