namespace:
  create: true
  name: whoami

image:
  repository: docker.io/traefik/whoami
  tag: v1.11.0
  pullPolicy: IfNotPresent

replicaCount: 1

nodeSelector:
  kubernetes.io/hostname: k8s-worker-01

service:
  name: whoami
  port: 80
  targetPort: 80

httpRoute:
  enabled: true
  name: whoami
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: public-gateway
      namespace: gateway-system
      sectionName: http
  hostnames:
    - whoami.seung.site
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: whoami
          port: 80
          weight: 1
