namespace:
  create: true
  name: hunsy-realestate-proto

image:
  repository: ghcr.io/hunsy9/hunsy-realestate-proto
  tag: web-latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-pull-secret

replicaCount: 1

serviceAccount:
  name: hunsy-realestate-proto

nodeSelector:
  kubernetes.io/hostname: k8s-worker-01

service:
  name: hunsy-realestate-proto
  port: 80
  targetPort: 8080

httpRoute:
  enabled: true
  name: hunsy-realestate-proto
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: public-gateway
      namespace: gateway-system
      sectionName: http
  hostnames:
    - proto.seung.site
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: hunsy-realestate-proto
          port: 80
          weight: 1

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi
