namespace:
  create: false
  name: hunsy-hermes-runtime

image:
  repository: ghcr.io/hunsy9/hunsy-app-launcher
  tag: web-sha-07f84b3
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-pull-secret

replicaCount: 1

serviceAccount:
  name: hunsy-app-launcher

nodeMetrics:
  enabled: true

nodeSelector:
  kubernetes.io/hostname: k8s-worker-01

service:
  name: hunsy-app-launcher
  port: 80
  targetPort: 8080

httpRoute:
  enabled: true
  name: hunsy-app-launcher
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: public-gateway
      namespace: gateway-system
      sectionName: http
  hostnames:
    - app.seung.site
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/asset
      backendRefs:
        - group: ""
          kind: Service
          name: hunsy-app-launcher
          port: 80
          weight: 1
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: hunsy-app-launcher
          port: 80
          weight: 1

resources:
  requests:
    cpu: 10m
    memory: 24Mi
  limits:
    cpu: 200m
    memory: 160Mi
