apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: registry-1.docker.io/envoyproxy
      chart: gateway-helm
      targetRevision: v1.8.4
      helm:
        releaseName: eg
        valueFiles:
          - $values/sites/az/envoy-gateway/values.yaml
    - repoURL: https://github.com/hunsy9/hunsy-homelab.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
